### ISSUE TITLE
1.0.5一直提示cpu限制

### ISSUE THREAD

**Issue by superggh** [itleaks/eos-contract#1]
你好，我按你的方法，可是还是一直提示Error 3081001: transaction reached the deadline set due to leeway on account CPU limits，谢谢指教

**Comment by itleaks** [comment]
@superggh  这种方法确实是需要很合适的时机才可以成功，因为目前系统设置了一个leeway时间限制，就是transaction的最长cpu执行时间leeway(3000us) ，也就是说buyram和buycpu两个action的时间不能超过3000us,通常情况下这两个action耗时4500+us，除非节点机器够强悍，负载够轻才可能将这个执行时间降到3000us以下，这种情况下才能成功，可见需要把握这种时机才能成功

**Comment by itleaks** [comment]
该方法目前已经基本不可行，大家把它当做练习的实践吧
